param(
    [string]$OutputPath = "",
    [switch]$IncludeAllProperties
)

$ErrorActionPreference = "Stop"

if (-not $OutputPath) {
    $OutputPath = Join-Path $PSScriptRoot "windows-devices.json"
}

function Convert-ToPlainObject($InputObject) {
    if ($null -eq $InputObject) {
        return $null
    }

    $result = [ordered]@{}
    foreach ($property in $InputObject.PSObject.Properties) {
        $value = $property.Value
        if ($value -is [System.Array]) {
            $result[$property.Name] = @($value)
        } else {
            $result[$property.Name] = $value
        }
    }
    return $result
}

$presentDevices = Get-PnpDevice -PresentOnly |
    Sort-Object Class, FriendlyName, InstanceId |
    ForEach-Object {
        $device = [ordered]@{
            Status = $_.Status
            Class = $_.Class
            FriendlyName = $_.FriendlyName
            InstanceId = $_.InstanceId
            Manufacturer = $_.Manufacturer
            Service = $_.Service
        }

        if ($IncludeAllProperties) {
            $device.Properties = Convert-ToPlainObject $_
        }

        [pscustomobject]$device
    }

$serialPorts = @(Get-CimInstance Win32_SerialPort -ErrorAction SilentlyContinue |
    Sort-Object DeviceID |
    Select-Object DeviceID, Name, Description, PNPDeviceID, ProviderType)

$disks = @(Get-Disk -ErrorAction SilentlyContinue |
    Sort-Object Number |
    Select-Object Number, FriendlyName, SerialNumber, BusType, PartitionStyle, OperationalStatus, Size)

$monitors = @(Get-CimInstance -Namespace root\wmi -ClassName WmiMonitorBasicDisplayParams -ErrorAction SilentlyContinue |
    Sort-Object InstanceName |
    Select-Object InstanceName, Active, MaxHorizontalImageSize, MaxVerticalImageSize)

$cameras = @($presentDevices | Where-Object {
    $_.Class -in @("Camera", "Image", "MEDIA") -or
    $_.FriendlyName -match "camera|webcam|摄像|相机"
})

$audio = @($presentDevices | Where-Object {
    $_.Class -in @("AudioEndpoint", "MEDIA") -or
    $_.FriendlyName -match "microphone|speaker|audio|麦克风|扬声器|耳机"
})

$usb = @($presentDevices | Where-Object {
    $_.InstanceId -like "USB\*" -or $_.Class -eq "USB"
})

$snapshot = [ordered]@{
    SchemaVersion = 1
    GeneratedAt = (Get-Date).ToString("o")
    ComputerName = $env:COMPUTERNAME
    UserName = $env:USERNAME
    Notes = @(
        "Generated by docs/codex-wsl/windows-device-bridge/export-windows-devices.ps1",
        "Local machine snapshot. Do not commit windows-devices.json if it contains private hardware identifiers."
    )
    Counts = [ordered]@{
        PresentDevices = @($presentDevices).Count
        SerialPorts = @($serialPorts).Count
        Disks = @($disks).Count
        Monitors = @($monitors).Count
        Cameras = @($cameras).Count
        Audio = @($audio).Count
        Usb = @($usb).Count
    }
    PresentDevices = @($presentDevices)
    SerialPorts = @($serialPorts)
    Disks = @($disks)
    Monitors = @($monitors)
    Cameras = @($cameras)
    Audio = @($audio)
    Usb = @($usb)
}

$parent = Split-Path -Parent $OutputPath
if ($parent -and -not (Test-Path $parent)) {
    New-Item -ItemType Directory -Path $parent | Out-Null
}

$snapshot | ConvertTo-Json -Depth 8 | Set-Content -Path $OutputPath -Encoding UTF8
Write-Host "Wrote $OutputPath"
Write-Host "Present devices: $($snapshot.Counts.PresentDevices)"
Write-Host "Serial ports: $($snapshot.Counts.SerialPorts)"
Write-Host "USB devices: $($snapshot.Counts.Usb)"
