#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
json_path="$script_dir/windows-devices.json"
class_filter=""
grep_filter=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        --file)
            json_path="$2"
            shift 2
            ;;
        --class)
            class_filter="$2"
            shift 2
            ;;
        --grep)
            grep_filter="$2"
            shift 2
            ;;
        -h|--help)
            cat <<'USAGE'
Usage: read-windows-devices.sh [--file PATH] [--class CLASS] [--grep TEXT]

Summarizes a Windows device snapshot generated by export-windows-devices.ps1.
USAGE
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 2
            ;;
    esac
done

if [ ! -f "$json_path" ]; then
    echo "Missing snapshot: $json_path" >&2
    echo "Run export-windows-devices.ps1 from Windows PowerShell first." >&2
    exit 1
fi

if command -v jq >/dev/null 2>&1; then
    echo "Snapshot:"
    jq -r '"generated_at=\(.GeneratedAt) computer=\(.ComputerName) user=\(.UserName)"' "$json_path"
    jq -r '.Counts | to_entries[] | "\(.key)=\(.value)"' "$json_path"
    echo
    echo "Devices:"
    jq_filter='.PresentDevices[]'
    if [ -n "$class_filter" ]; then
        jq_filter="$jq_filter | select((.Class // \"\") == \"$class_filter\")"
    fi
    if [ -n "$grep_filter" ]; then
        jq_filter="$jq_filter | select(((.FriendlyName // \"\") + \" \" + (.InstanceId // \"\")) | test(\"$grep_filter\"; \"i\"))"
    fi
    jq -r "$jq_filter | [(.Class // \"\"), (.Status // \"\"), (.FriendlyName // \"\"), (.InstanceId // \"\")] | @tsv" "$json_path" |
        column -t -s $'\t'
else
    python3 - "$json_path" "$class_filter" "$grep_filter" <<'PY'
import json
import re
import sys

path, class_filter, grep_filter = sys.argv[1:4]
with open(path, "r", encoding="utf-8-sig") as fh:
    data = json.load(fh)

print("Snapshot:")
print(f"generated_at={data.get('GeneratedAt')} computer={data.get('ComputerName')} user={data.get('UserName')}")
for key, value in data.get("Counts", {}).items():
    print(f"{key}={value}")

pattern = re.compile(grep_filter, re.I) if grep_filter else None
print("\nDevices:")
for device in data.get("PresentDevices", []):
    cls = device.get("Class") or ""
    name = device.get("FriendlyName") or ""
    instance = device.get("InstanceId") or ""
    if class_filter and cls != class_filter:
        continue
    if pattern and not pattern.search(name + " " + instance):
        continue
    print(f"{cls:18} {device.get('Status') or '':8} {name}  {instance}")
PY
fi
